{{- if and .Values.gateway.enabled .Values.httproute.enabled .Values.httproute.tls.redirect }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-tls-redirect" (include "httproute.name" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: httproute
    prefect-version: {{ .Chart.AppVersion }}
    {{- if .Values.httproute.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.httproute.labels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.httproute.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.httproute.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.httproute.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  parentRefs:
  - name: {{ .Values.httproute.parentRefs | first | dig "name" (include "gateway.name" $) | quote }}
    {{- if ((.Values.httproute.parentRefs | first).namespace) }}
    namespace: {{ (.Values.httproute.parentRefs | first).namespace | quote }}
    {{- end }}
    sectionName: http
  {{- $hostnames := include "gateway.hostnames" . | fromYamlArray }}
  {{- if $hostnames }}
  hostnames:
  {{- range $hostnames }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        port: {{ .Values.httproute.tls.redirectPort | default 443 }}
        statusCode: 301
{{- end }}
