apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: server
    prefect-version: {{ .Chart.AppVersion }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.server.revisionHistoryLimit }}
  replicas: {{ .Values.sqlite.enabled | ternary 1 .Values.server.replicaCount }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  strategy: {{ toYaml .Values.controller.updateStrategy | nindent 4 }}
  template:
    metadata:
      {{- if .Values.server.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.server.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: server
        prefect-version: {{ .Chart.AppVersion }}
        {{- if .Values.server.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.server.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.prefect.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.global.prefect.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ template "server.serviceAccountName" . }}
      {{- if .Values.server.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.server.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.server.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.server.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.server.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.server.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.server.podSecurityContext }}
      securityContext: {{- .Values.server.podSecurityContext | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.server.priorityClassName }}
      priorityClassName: {{ .Values.server.priorityClassName }}
      {{- end }}
      containers:
        - name: prefect-server
          image: "{{ .Values.global.prefect.image.repository }}:{{ .Values.global.prefect.image.prefectTag }}"
          imagePullPolicy: {{ .Values.global.prefect.image.pullPolicy }}
          command:
            {{- if .Values.server.command }}
            {{- .Values.server.command | toYaml | nindent 12 }}
            {{- else }}
            - /usr/bin/tini
            - -g
            - --
            - /opt/prefect/entrypoint.sh
            {{- end }}
          args:
            {{- if .Values.server.args }}
            {{- .Values.server.args | toYaml | nindent 12 }}
            {{- else }}
            - prefect
            - server
            - start
            {{- if .Values.backgroundServices.runAsSeparateDeployment }}
            - --no-services
            {{- end }}
            - --port
            - {{ .Values.service.targetPort | quote }}
            {{- range .Values.server.extraArgs }}
            - {{ . | toString }}
            {{- end }}
            {{- end }}
          workingDir: /home/prefect
          ports:
            - containerPort: {{ int .Values.service.targetPort }}
          env:
            - name: HOME
              value: /home/prefect
            - name: PREFECT_DEBUG_MODE
              value: {{ .Values.server.debug | quote }}
            - name: PREFECT_LOGGING_SERVER_LEVEL
              value: {{ .Values.server.loggingLevel | quote }}
            - name: PREFECT_SERVER_API_BASE_PATH
              value: {{ .Values.server.apiBasePath | quote }}
            - name: PREFECT_SERVER_API_HOST
              value: 0.0.0.0
            - name: PREFECT_SERVER_API_PORT
              value: {{ .Values.service.targetPort | quote }}
            - name: PREFECT_UI_API_URL
              value: {{ .Values.server.uiConfig.prefectUiApiUrl | quote }}
            - name: PREFECT_UI_STATIC_DIRECTORY
              value: {{ .Values.server.uiConfig.prefectUiStaticDirectory | quote }}
            - name: PREFECT_API_DATABASE_CONNECTION_URL
              {{- if .Values.sqlite.enabled }}
              value: "sqlite+aiosqlite:////data/prefect.db"
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "server.postgres-string-secret-name" . }}
                  key: connection-string
              {{- end }}
            {{- if .Values.server.basicAuth.enabled }}
            - name: PREFECT_SERVER_API_AUTH_STRING
            {{- if .Values.server.basicAuth.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.server.basicAuth.existingSecret }}
                  key: auth-string
            {{- else }}
              value: {{ .Values.server.basicAuth.authString | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.global.prefect.env }}
            {{- include "common.tplvalues.render" (dict "value" .Values.global.prefect.env "context" $) | nindent 12 }}
            {{- end }}
            {{- if .Values.server.env }}
            {{- include "common.tplvalues.render" (dict "value" .Values.server.env "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.server.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.server.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.server.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.server.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.server.resources }}
          resources: {{- toYaml .Values.server.resources | nindent 12 }}
          {{- end }}
          {{- with .Values.server.containerSecurityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.server.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.server.apiBasePath }}/health
              port: {{ .Values.service.targetPort }}
          {{- toYaml .Values.server.livenessProbe.config | nindent 12 }}
          {{- end }}
          {{- if .Values.server.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.server.apiBasePath }}/ready
              port: {{ .Values.service.targetPort }}
          {{- toYaml .Values.server.readinessProbe.config | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /home/prefect
              name: scratch
              subPathExpr: home
            - mountPath: /tmp
              name: scratch
              subPathExpr: tmp
            - mountPath: {{ .Values.server.uiConfig.prefectUiStaticDirectory }}
              name: scratch
              subPathExpr: ui-build
            {{- if .Values.sqlite.enabled }}
            - mountPath: /data
              name: sqlite-storage
            {{- end }}
          {{- if .Values.server.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.server.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.server.extraContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.server.extraContainers "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: scratch
          emptyDir: {}
        {{- if .Values.sqlite.enabled }}
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: {{ template "common.names.fullname" . }}-sqlite
        {{- end }}
        {{- if .Values.server.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.server.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
