apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: orion
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.orion.autoscaling.enabled }}
  replicas: {{ .Values.orion.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: orion
  template:
    metadata:
      {{- if .Values.orion.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.orion.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: orion
        {{- if .Values.orion.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.orion.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
    {{- if .Values.orion.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.orion.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
    {{- end }}
      serviceAccountName: {{ template "orion.serviceAccountName" . }}
      {{- if .Values.orion.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.orion.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.orion.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.orion.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.orion.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.orion.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.orion.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.orion.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: prefect-orion
          image: "{{ .Values.orion.image.repository }}:{{ .Values.orion.image.tag }}"
          imagePullPolicy: {{ .Values.orion.image.pullPolicy }}
          command: ["prefect", "orion", "start", "--host", "0.0.0.0", "--log-level", "WARNING", "--port", {{ .Values.service.port | quote }}]
          ports:
            - containerPort: {{ int .Values.service.port }}
          env:
            - name: PREFECT_DEBUG_MODE
              value: {{ .Values.orion.image.debug | quote }}
            {{- if .Values.postgresql.enabled }}
            - name: PREFECT_ORION_DATABASE_CONNECTION_URL
              valueFrom:
                {{- include "orion.postgres-secret-ref" . | nindent 4 }}
            {{- end }}
            {{- if .Values.orion.env }}
            {{- include "common.tplvalues.render" (dict "value" .Values.orion.env "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.orion.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.orion.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.orion.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.orion.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.orion.resources }}
          resources: {{- toYaml .Values.orion.resources | nindent 12 }}
          {{- end }}
