apiVersion: v2
name: prefect-orion
description: Prefect orion application bundle
type: application
home: https://github.com/PrefectHQ
version: 0.0.0
appVersion: "latest"
maintainers:
  - name: gabcoyne
    email: george@prefect.io
  - name: jamiedick
    email: jamie@prefect.io
sources:
  - https://github.com/PrefectHQ/prefect-helm
dependencies:
- name: postgresql
  version: "~11.6.2"
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.useSubChart
