apiVersion: v2
appVersion: 2-latest
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.2.1
  - name: postgresql
    condition: postgresql.enabled,postgresql.useSubChart
    repository: https://charts.bitnami.com/bitnami
    version: 11.9.13
description: Prefect orion application bundle
engine: gotpl
home: https://github.com/PrefectHQ
maintainers:
  - name: gabcoyne
    email: george@prefect.io
  - name: jamiezieziula
    email: jamie@prefect.io
name: prefect-orion
sources:
  - https://github.com/PrefectHQ/prefect-helm
type: application
# This version is never actually shipped. github actions will package add the appropriate version at build-time
version: 0.0.0
