apiVersion: v2
name: prefect-agent
description: Prefect orion application bundle
type: application
home: https://github.com/PrefectHQ
version: 2022.7.29
appVersion: "latest"
maintainers:
  - name: gabcoyne
    email: george@prefect.io
sources:
  - https://github.com/PrefectHQ/prefect-helm
