name: Lint and Test Prefect Agent Chart

on:
  pull_request:
    paths:
      - .github/workflows/agent-lint-and-test.yaml
      - .github/linters/agent-ct.yaml
      - 'charts/prefect-agent/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.3
        with:
          version: v3.9.2

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.0

      - name: Run chart-testing (lint)
        run: ct lint --config .github/linters/agent-ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.3.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Create API Secret for Agent Chart
        run: |
          kubectl create ns prefect
          kubectl create secret generic prefect-api-key  --from-literal=key=${{ secrets.PREFECT_CLOUD_API_KEY }} -n prefect

      - name: Run chart-testing (install)
        run: ct install --config .github/linters/agent-ct.yaml --helm-extra-set-args "--set=agent.config.workQueueName=test-helm --set=agent.config.accountId=${{ secrets.PREFECT_CLOUD_ACCOUNT_ID }} --set=agent.config.workspaceId=${{ secrets.PREFECT_CLOUD_WORKSPACE_ID }}"
