name: Lint and Test Prefect Server Chart

"on":
  pull_request:
    paths:
      - .github/workflows/prometheus-prefect-exporter-lint-and-test.yaml
      - .github/linters/prometheus-prefect-exporter-ct.yaml
      - charts/prometheus-prefect-exporter/**

jobs:
  lint_test:
    name: "lint-test (${{ matrix.kubernetes }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes:
          - "1.25.8"
          - "1.26.3"
          - "1.27.0"
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3.5

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --config .github/linters/prometheus-prefect-exporter-ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          node_image: "kindest/node:v${{ matrix.kubernetes }}"

      - name: Run chart-testing (install)
        run: |
          helm install prefect-server -n default ./charts/prefect-server/ --set=postgresql.auth.password=TESTING
          ct install --config .github/linters/prometheus-prefect-exporter-ct.yaml --helm-extra-set-args "--set=prefectApiUrl=http://prefect-server.default.svc.cluster.local:4200/api"
