---
name: Updatecli major dependency updates

on:
  workflow_dispatch:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │  ┌───────────── day of the month (1 - 31)
    #        │  │  │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │  │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │  │ │ │
    #        │  │  │ │ │
    #        │  │  │ │ │
    - cron: "0 15 1 * *" # The first of each month at 10am EST

permissions:
  contents: read

jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%-m-%-d')" >> $GITHUB_OUTPUT

      - name: install updatecli in the runner
        uses: updatecli/updatecli-action@v2

      - name: run updatecli in diff mode
        run: |
          updatecli diff --config .github/updatecli/manifest-major.yaml
        env:
          GITHUB_TOKEN: ${{ github.token }}
