name: Lint and Test Prefect Worker Chart

"on":
  pull_request:
    paths:
      - .github/workflows/worker-lint-and-test.yaml
      - .github/linters/worker-ct.yaml
      - charts/prefect-worker/**
jobs:
  lint_test:
    name: "lint-test (${{ matrix.kubernetes }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes:
          - "1.25.8"
          - "1.26.3"
          - "1.27.0"
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3.5

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (lint)
        run: ct lint --config .github/linters/worker-ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          node_image: "kindest/node:v${{ matrix.kubernetes }}"

      - name: Create API Secret for Agent Chart
        run: |
          kubectl create ns prefect
          kubectl create secret generic prefect-api-key  --from-literal=key=${{ secrets.PREFECT_CLOUD_API_KEY }} -n prefect

      - name: Run chart-testing (install)
        run: ct install --config .github/linters/worker-ct.yaml --helm-extra-set-args "--set=worker.config.workPool=test-helm --set=worker.cloudApiConfig.accountId=${{ secrets.PREFECT_CLOUD_ACCOUNT_ID }} --set=worker.cloudApiConfig.workspaceId=${{ secrets.PREFECT_CLOUD_WORKSPACE_ID }}"
